Re-Arranged Base Models
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
coverage.Contract.buyer: (fields.E304) Reverse accessor 'Entity.contract_set' for 'coverage.Contract.buyer' clashes with reverse accessor for 'coverage.Contract.seller'.
        HINT: Add or change a related_name argument to the definition for 'coverage.Contract.buyer' or 'coverage.Contract.seller'.
coverage.Contract.seller: (fields.E304) Reverse accessor 'Entity.contract_set' for 'coverage.Contract.seller' clashes with reverse accessor for 'coverage.Contract.buyer'.
        HINT: Add or change a related_name argument to the definition for 'coverage.Contract.seller' or 'coverage.Contract.buyer'.
coverage.Policy.insured: (fields.E304) Reverse accessor 'Entity.policy_set' for 'coverage.Policy.insured' clashes with reverse accessor for 'coverage.Policy.provider'.
        HINT: Add or change a related_name argument to the definition for 'coverage.Policy.insured' or 'coverage.Policy.provider'.
coverage.Policy.provider: (fields.E304) Reverse accessor 'Entity.policy_set' for 'coverage.Policy.provider' clashes with reverse accessor for 'coverage.Policy.insured'.
        HINT: Add or change a related_name argument to the definition for 'coverage.Policy.provider' or 'coverage.Policy.insured'.
coverage.Shipment.disport: (fields.E304) Reverse accessor 'Location.shipment_set' for 'coverage.Shipment.disport' clashes with reverse accessor for 'coverage.Shipment.loadport'.
        HINT: Add or change a related_name argument to the definition for 'coverage.Shipment.disport' or 'coverage.Shipment.loadport'.
coverage.Shipment.loadport: (fields.E304) Reverse accessor 'Location.shipment_set' for 'coverage.Shipment.loadport' clashes with reverse accessor for 'coverage.Shipment.disport'.
        HINT: Add or change a related_name argument to the definition for 'coverage.Shipment.loadport' or 'coverage.Shipment.disport'.
coverage.Shipment.surveyor_disport: (fields.E304) Reverse accessor 'Entity.shipment_set' for 'coverage.Shipment.surveyor_disport' clashes with reverse accessor for 'coverage.Shipment.surveyor_loadport'.
        HINT: Add or change a related_name argument to the definition for 'coverage.Shipment.surveyor_disport' or 'coverage.Shipment.surveyor_loadport'.
coverage.Shipment.surveyor_loadport: (fields.E304) Reverse accessor 'Entity.shipment_set' for 'coverage.Shipment.surveyor_loadport' clashes with reverse accessor for 'coverage.Shipment.surveyor_disport'.
        HINT: Add or change a related_name argument to the definition for 'coverage.Shipment.surveyor_loadport' or 'coverage.Shipment.surveyor_disport'.